sudo: required
services:
  - docker

before_install:
  - docker build -t lyndonoc/hashrator-server -f ./server/Dockerfile ./server

script:
  - docker run --env MOCKED_RESPONSE --env MOCKED_PARSED_DATA --env TAG_SEARCH_MORE_PAYLOAD_SHAPE --env TAG_SEARCH_NODE_SHAPE --env TAG_SEARCH_TOP_PAYLOAD_SHAPE lyndonoc/hashrator-server npm run test

after_success:
  - docker build -t lyndonoc/hashrator-client -f ./client/Dockerfile ./client
  - docker build -t lyndonoc/hashrator-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t lyndonoc/hashrator-server -f ./server/Dockerfile ./server
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker push lyndonoc/hashrator-client
  - docker push lyndonoc/hashrator-nginx
  - docker push lyndonoc/hashrator-server

deploy:
  - provider: elasticbeanstalk
    access_key_id:
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
    region: "us-east-1"
    app: "hashrator"
    env: "Hashrator-env-1"
    bucket_name: "elasticbeanstalk-us-east-1-383455664321"
    bucket_path: "hashrator"
