sudo: required
services:
  - docker

before_install:
  - docker build -t lyndonoc/hashrator-backend -f Dockerfile .

script:
  - docker run lyndonoc/hashrator-backend npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-east-1"
  app: "hashrator"
  env: "Hashrator-env"
  bucket_name: "elasticbeanstalk-us-east-1-383455664321"
  bucket_path: "hashrator"
